[package]
name = "rusty-post-lib"
version = "0.1.0"
authors = ["jonnywalker"]

[dependencies]
curl = "0.4.1"
futures = "0.1.11"
tokio-curl = "0.1"
log = "0.3"
tokio-io = "0.1"
tokio-core = "0.1"

[dev-dependencies]
env_logger = { version = "0.3", default-features = false }
